[EventHub] migrate from WindowsAzure.ServiceBus to Azure.Messaging.EventHubs
Azure-Samples/service-fabric-dotnet-iot pull request #36
Opened 2021-10-27 03:00 UTC by zedy-wj

1.Upgrade EventHub sdk to t2.

2.Updated files: 

- IngestionController.cs 
- Iot.Admin.WebService.csproj 
- Iot.Ingestion.RouterService/App.config
- Iot.Ingestion.RouterService.csproj 
- RouterService.cs
- Iot.Ingestion.RouterService/packages.config

@scottaddie, @AlexGhiondea, @lilyjma, @ramya-rao-a, @jsquire for notification

2021-10-27 18:45 UTC, ramya-rao-a commented
@jsquire, Please review

2021-11-02 14:07 UTC, jsquire requested changes
I don't believe this is a scenario where doing a straight "change one SDK version to another" will be an effective approach.    There are some fundamental flaws in this sample that need to be addressed;  we'll want to consider a rewrite.

As it stands, I'm reasonably sure that this hasn't been run and validated;  there are several areas that would result in an immediate failure.    Before asking for re-review, please ensure that you're able to compile and run the sample.

2021-11-02 14:07 UTC, jsquire commented on src/Iot.Admin.WebService/Controllers/IngestionController.cs
> +            EventHubProducerClient producer = new EventHubProducerClient(parameters.IotHubConnectionString, "eventHubName");
This will not work;  the Event Hubs clients cannot take an IoT Hub connection string directly.    We'll want to update this with comments on how to obtain the proper connection string.   

see: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-read-builtin#read-from-the-built-in-endpoint

2021-11-02 14:07 UTC, jsquire commented on src/Iot.Admin.WebService/Iot.Admin.WebService.csproj
> +    <TargetFramework>net472</TargetFramework>
Why was `net472` chosen?   Did we consider `net5.0` or `netcoreapp3.1`?

2021-11-02 14:07 UTC, jsquire commented on src/Iot.Ingestion.RouterService/App.config
> +        <bindingRedirect oldVersion="0.0.0.0-4.0.5.1" newVersion="4.0.5.1" />
This version of `System.Text.Encodings.Web` has a known vulnerability discussed in [ CVE-2021-26701](https://github.com/advisories/GHSA-ghhp-997w-qr28) and needs to be bumped to 4.5.1 at a minimum if we're sticking with `net472` as a target platform.

2021-11-02 14:07 UTC, jsquire commented on src/Iot.Ingestion.RouterService/Iot.Ingestion.RouterService.csproj
>      <AppDesignerFolder>Properties</AppDesignerFolder>
This project file is very old and should be regenerated.

2021-11-02 14:07 UTC, jsquire commented on src/Iot.Ingestion.RouterService/RouterService.cs
> +
```suggestion
```

2021-11-02 14:07 UTC, jsquire commented on src/Iot.Ingestion.RouterService/RouterService.cs
> +                            await foreach (PartitionEvent receivedEvent in eventHubConsumerClient.ReadEventsAsync(cancellationSource.Token))
We do not want to recommend use of `ReadEventsAsync` in production code.  As we discuss in the [documentation](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.consumer.eventhubconsumerclient.readeventsasync), this method is intended to be used for exploration only;  if we're going to include it here to reduce complexity, we need to reflect the `Remarks` from the docs to call that out clearly.

2021-11-02 14:07 UTC, jsquire commented on src/Iot.Ingestion.RouterService/RouterService.cs
>          /// <param name="epochDictionary"></param>
These empty comment blocks offer no value.   Please add content or remove them.

2021-11-02 14:07 UTC, jsquire commented on src/Iot.Ingestion.RouterService/RouterService.cs
> +                eventHubConsumerClient = await this.ConnectToIoTHubAsync(iotHubConnectionString, servicePartitionKey, epochDictionary, offsetDictionary);
This will not work;  the Event Hubs clients cannot take an IoT Hub connection string directly.    We'll want to update this with comments on how to obtain the proper connection string.   

see: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-read-builtin#read-from-the-built-in-endpoint

2021-11-02 14:07 UTC, jsquire commented on src/Iot.Ingestion.RouterService/RouterService.cs
> +            var producer = new EventHubProducerClient(connectionString, eventHubName);
This client is never closed/disposed and will leak a connection.

2021-11-02 14:07 UTC, jsquire commented on src/Iot.Ingestion.RouterService/RouterService.cs
>          /// <param name="epochDictionary"></param>
This method should clearly document that callers have responsibility for closing/disposing the returned consumer.

2021-11-02 14:07 UTC, jsquire commented on src/Iot.Ingestion.RouterService/RouterService.cs
> +        private async Task<EventHubConsumerClient> ConnectToIoTHubAsync(
This name is incorrect;  the method creates a client but does not perform an active operation with it.  As such, no connection to the Event Hub is made.     Also, there is no communication with IoT Hub in this flow, nor will the Event Hubs clients do so.

2021-11-02 14:07 UTC, jsquire commented on src/Iot.Ingestion.RouterService/RouterService.cs
>                  await epochDictionary.SetAsync(tx, "epoch", newEpoch);
This doesn't make sense in context;  the client is being created and no owner level (epoch) is in use.   The majority of this method is pretty much a no-op.

2021-11-02 14:07 UTC, jsquire commented on src/Iot.Ingestion.RouterService/packages.config
> +  <package id="System.ValueTuple" version="4.5.0" targetFramework="net472" />
We definitely shouldn't be mixing targets of `net452` and `net472` here.

2021-11-02 14:07 UTC, jsquire commented on src/Iot.Ingestion.RouterService/packages.config
>    <package id="Microsoft.Azure.KeyVault.Core" version="2.0.4" targetFramework="net452" />
This package is [formally deprecated](https://www.nuget.org/packages/Microsoft.Azure.KeyVault.Core) and shouldn't be used in a sample.   We should move to the  `Azure.Security.KeyVault` family of packages.

2021-12-06 07:43 UTC, zedy-wj commented
Hi, @jsquire - 
We are very sorry for the lack of rigor in the last migration, we confused `iot hub` and `event hub`, which leads to some areas failure. This time, we use the sample of `EventProcessorClient` to realize the `RouterService` logic. We have updated most of them based on your comments. And all files were passed in compiling. Now, we have two questions to communicate with you.
1.We could not run the sample with clusters which described in `README`. We blocked at start `FabricHostSvc` service. Please help provide some suggestions on running the sample.
2.For legacy framework upgrades, this is also extremely time-consuming, we have upgraded project `Iot.Admin.WebService` to `netcoreapp3.1`, but project `Iot.Ingestion.RouterService` was too complex to upgrade, considering consistency, I upgraded them to framework4.7.2. We will consider again after all migrations have been completed.

2021-12-06 07:49 UTC, zedy-wj commented on src/Iot.Admin.WebService/Iot.Admin.WebService.csproj
> +    <TargetFramework>net472</TargetFramework>
For legacy framework upgrades, this is also extremely time-consuming, we have upgraded project `Iot.Admin.WebService` to `netcoreapp3.1`, but project `Iot.Ingestion.RouterService` was too complex to upgrade, considering consistency, I upgraded them to framework4.7.2.

2021-12-17 09:53 UTC, zedy-wj commented
@jsquire - Do you have any ideas about run the sample with clusters?

2022-01-03 16:26 UTC, jsquire commented
@zedy-wj:  I'm not sure what `clusters` refers to in this context.   I'd assume that following the sample article would walk through creating any Azure resources needed to run the sample - otherwise, how would the audience know what to do?    Is that not the case here?

2022-01-06 10:17 UTC, zedy-wj commented
@jsquire - The cluster here refers to the cluster that runs the example in the sample article. We follow the tutorial to create resources step by step. In the deployment step, we need a running local cluster. We keep failing when starting the local cluster. 

**Error Message**
![image](https://user-images.githubusercontent.com/81678720/148367098-310fa5d3-12f0-4e43-8c09-51e61b4e8c2a.png)


Do you know anyone who can provide some help, or is there a way to run the example without using a cluster?

2022-01-06 15:18 UTC, jsquire commented
@zedy-wj:  Unfortunately, I don't have much familiarity with Service Fabric and the above doesn't tell me much.   From the commit history, it looks like Vaclav Turecek from the Service Fabric team did much of the initial work on the sample.   You may want to consider reaching out to him to discuss.

2022-01-07 09:37 UTC, zedy-wj commented
@vturecek - Could you provide some help about how to start cluster, for detailed information, please refer to : https://github.com/Azure-Samples/service-fabric-dotnet-iot/pull/36#issuecomment-1006444605, thanks.

2022-02-11 10:02 UTC, zedy-wj commented
@vturecek - Could you provide some help about how to start cluster or is there a way to run the example without using a cluster? Thanks a lot!

2022-02-25 08:39 UTC, v-xuto commented
@vturecek - Could you provide some help about how to start cluster or is there a way to run the example without using a cluster? Thanks in advance.

2022-03-15 09:17 UTC, v-xuto commented
@vturecek - Could you provide some help about how to start cluster or is there a way to run the example without using a cluster? Thanks in advance.

2022-04-01 08:32 UTC, v-xuto commented
@vturecek - Could you provide some help about how to start cluster or is there a way to run the example without using a cluster? Thanks in advance.

2022-04-29 10:30 UTC, v-xuto commented
@vturecek - Could you provide some help about how to start cluster or is there a way to run the example without using a cluster? Thanks in advance.

2024-11-05 06:41 UTC, closed without merging